apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-dev
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 8081  # External port for development
    targetPort: 8081  # Internal container port, matches the environment variable in the deployment patch
  type: LoadBalancer
