apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: giuffrelab/flask-web-app:v1
          env:
            - name: PORT
              value: "8080"  # Keeping the port configuration
          ports:
            - containerPort: 8080
