apiVersion: v1
kind: Service
metadata:
  name: flask-app-service-prod
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 8082  # External port for production
    targetPort: 8082  # Internal container port, matches the environment variable in the deployment patch
  type: LoadBalancer
